# Generated by Django 2.0.4 on 2018-04-11 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tel', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('Introduction', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='papers')),
                ('peoplenum', models.IntegerField()),
                ('paymethod', models.CharField(max_length=200)),
                ('jobdate', models.DateField()),
                ('jobtime', models.TimeField()),
                ('overtime', models.DateTimeField()),
                ('commission', models.CharField(max_length=200)),
                ('treatment', models.IntegerField()),
                ('treatmentType', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=200)),
                ('communicate', models.CharField(max_length=200)),
                ('communicatenum', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('tel', models.IntegerField()),
                ('size', models.CharField(max_length=200)),
                ('openid', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('Introduction', models.CharField(max_length=500)),
                ('headerName', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='papers')),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('signtime', models.DateTimeField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapi.Job')),
                ('merchants_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('tel', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('openid', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
